# Generated by Django 4.2.4 on 2023-08-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('points', models.IntegerField()),
                ('question_type', models.CharField(max_length=30)),
                ('answers', models.TextField()),
                ('righ_answers', models.TextField()),
                ('right_answer_full', models.TextField()),
            ],
        ),
    ]
