# Generated by Django 4.2.4 on 2023-08-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_path',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='righ_answers',
            field=models.TextField(null=True),
        ),
    ]
