# Generated by Django 4.2.4 on 2023-08-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_question_image_path_alter_question_answers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('category', models.TextField(null=True)),
                ('icon_path', models.CharField(max_length=40)),
            ],
        ),
    ]
